# Generated by Django 3.2.14 on 2022-07-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
    ]
